# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b84a0d1a2cc9b289894d1cf789aae77cdf36541d98ea433464e9aa1346d072779b25a78614e62d5984967292f76c004b9372e11cbd87f1553f45711e7d60e43

test:
  secret_key_base: 3a4c53dcbc1f9bfdb823bb3a45c7bda46cd5647187f4e65be222d55c6c2c35fce94675ffb0e09fe4a7a467a37d8bc4ca9cfdac67508ab86f5d4783cded56a86f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
